service: service-name-v1
runtime: nodejs
env: flex

# Prod env settings
automatic_scaling:
  min_num_instances: 2
  max_num_instances: 20
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.7

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 1
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 50