apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
# FleetAutoscaler Metadata
# https://v1-16.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#objectmeta-v1-meta
metadata:
  namespace: <NAME>-<ENV>
  name: <NAME>-fleet-<URL_VERSION>-autoscaler
  labels:
    app.kubernetes.io/name: <NAME>
    app.kubernetes.io/version: <VERSION>
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: gocd
    forhumans/build: "<SHORT_SHA>"
    forhumans/in-use: "true"
spec:
  # The name of the fleet to attach to and control. Must be an existing Fleet in the same namespace
  # as this FleetAutoscaler
  fleetName: <NAME>-fleet-<URL_VERSION>
  # The autoscaling policy
  policy:
    # type of the policy. for now, only Buffer is available
    type: Buffer
    # parameters of the buffer policy
    buffer:
      # Size of a buffer of "ready" game server instances
      # The FleetAutoscaler will scale the fleet up and down trying to maintain this buffer, 
      # as instances are being allocated or terminated
      # it can be specified either in absolute (i.e. 5) or percentage format (i.e. 5%)
      bufferSize: 2
      # minimum fleet size to be set by this FleetAutoscaler. 
      # if not specified, the actual minimum fleet size will be bufferSize
      minReplicas: 2
      # maximum fleet size that can be set by this FleetAutoscaler
      # required
      maxReplicas: 20