# Dockerfile extending the generic Node image with application files for a
# single application.
FROM node:10.18.1-buster

COPY . /app/

WORKDIR /app

ENV NPM_TOKEN zxBEd6yrWCcmIxwPMPgrRTCpWLiHtbQ0ziMJvwn+tYAN/y5bCY4CrN1NIIhz/zXlJCGrO754fBzV9y04IZUHJHi7mvpAqzHUZeCXM3/Py2Q=
ENV NODE_ENV test

RUN yarn --unsafe-perms --frozen-lockfile || \
  ((if [ -f yarn-debug.log ]; then \
      cat yarn-debug.log; \
    fi) && false)

CMD npm test
