# syntax=docker/dockerfile:experimental
# Must run with DOCKER_BUILDKIT=1 defined (or enabled in daemon config)
# e.g. DOCKER_BUILDKIT=1 docker build --secret id=npmtoken,src=/Users/tapps/.npm_token -t <tag> --progress plain ./
FROM gcr.io/forhumans-infrastructure/node-test-base:latest

ENV NODE_ENV test
ENV NPM_TOKEN placeholder
ENV GOOGLE_CLOUD_PROJECT forhumans-gameservices-dev

COPY --chown=${USER_ID}:${USER_GID} . /app/
WORKDIR /app/

RUN --mount=type=secret,id=npmtoken,mode=666 \
  NPM_TOKEN=$(cat /run/secrets/npmtoken) yarn --unsafe-perms --frozen-lockfile || \
  ((if [ -f yarn-debug.log ]; then \
      cat yarn-debug.log; \
    fi) && false)

CMD ["yarn", "test"]