apiVersion: v1
kind: ConfigMap
metadata:
  name: <NAME>-config-<URL_VERSION>
  namespace: <NAME>-<ENV>
  labels:
    app.kubernetes.io/name: <NAME>
    app.kubernetes.io/version: <VERSION>
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: gocd
    forhumans/build: "<SHORT_SHA>"
    forhumans/in-use: "true"
data:
  config.json: |
    {
      "loggingEnableConsole": true,
      "loggingEnableFiles": false,
      "serverProcesses": 2,
      "forceLocalConfig": false,
      "loggingLevel": "debug",
      "serverEnableDatadog": false,
      "apiUrl": "http://storage-battles.storage-battles-stag.svc.cluster.local",
      "bundleId": "com.byaliens.bid.wars.stars.multiplayer.auction.battles",
      "ignoreAgones": false
    }
  .env: |
    ENV=stag
    PORT=2567
    GOOGLE_APPLICATION_CREDENTIALS=/var/secrets/google/key.json
    GOOGLE_CLOUD_PROJECT=forhumans-gameservices-stag
    DATASTORE_PROJECT_ID=forhumans-gameservices-stag
    SERVICE_NAME=<NAME>
    SERVICE_DEPLOY_ID=<NAME>-v<MAJOR_VERSION>
    SERVICE_DEPLOY_VERSION=<VERSION>
    SERVICE_MAJOR_VERSION=<MAJOR_VERSION>
    SERVICE_VERSION=<VERSION>