apiVersion: v1
kind: ConfigMap
metadata:
  name: config-<NAME>-<URL_VERSION>
  namespace: default
data:
  config.json: |
    {
      "loggingEnableConsole": true,
      "loggingEnableFile": false,
      "serverProcesses": 2,
      "forceLocalConfig": false,
      "loggingLevel": "debug",
      "serverEnableDatadog": false,
      "apiUrl": "https://storage-battles-v1.stag.gameservices.forhumans.games",
      "bundleId": "com.megastorm.bidpvp.powerups",
      "ignoreAgones": true
    }
  .env: |
    ENV=stag
    PORT=2567
    GOOGLE_APPLICATION_CREDENTIALS=/var/secrets/google/key.json
    GOOGLE_CLOUD_PROJECT=forhumans-gameservices-stag
    DATASTORE_PROJECT_ID=forhumans-gameservices-stag
    SERVICE_NAME=<NAME>
    SERVICE_DEPLOY_ID=<NAME>-v<MAJOR_VERSION>
    SERVICE_DEPLOY_VERSION=<BUILD_VERSION>
    SERVICE_MAJOR_VERSION=<MAJOR_VERSION>
    SERVICE_VERSION=<BUILD_VERSION>
