apiVersion: v1
kind: ConfigMap
metadata:
  name: <NAME>-config-<URL_VERSION>
  namespace: default
  labels:
    tags.datadoghq.com/env: <ENV>
    tags.datadoghq.com/service: <NAME>
    tags.datadoghq.com/version: <VERSION>
    app.kubernetes.io/name: <NAME>
    app.kubernetes.io/version: <VERSION>
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: gocd
    forhumans/build: "<BUILD_NUMBER>"
    forhumans/in-use: "true"
data:
  config.json: |
    {
      "loggingEnableConsole": true,
      "loggingEnableFile": false,
      "serverProcesses": 2,
      "forceLocalConfig": false,
      "loggingLevel": "debug",
      "serverEnableDatadog": false,
      "apiUrl": "https://storage-battles.dev.gameservices.forhumans.games",
      "bundleId": "com.byaliens.bid.wars.stars.multiplayer.auction.battles",
      "ignoreAgones": false
    }
  .env: |
    ENV=dev
    PORT=2567
    GOOGLE_APPLICATION_CREDENTIALS=/var/secrets/google/key.json
    GOOGLE_CLOUD_PROJECT=forhumans-gameservices-dev
    DATASTORE_PROJECT_ID=forhumans-gameservices-dev
    SERVICE_NAME=<NAME>
    SERVICE_DEPLOY_ID=<NAME>-v<MAJOR_VERSION>
    SERVICE_DEPLOY_VERSION=<BUILD_VERSION>
    SERVICE_MAJOR_VERSION=<MAJOR_VERSION>
    SERVICE_VERSION=<BUILD_VERSION>
