apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  labels:
    app: <NAME>-<URL_VERSION>
  name: <NAME>-fleet-<URL_VERSION>
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        ad.datadoghq.com/<NAME>-<URL_VERSION>.logs: '[{"service":"<NAME>", "source":"nodejs"}]'
      labels:
        ssg.bundleid: com.byaliens.bid.wars.stars.multiplayer.auction.battles
        version: <BUILD_VERSION>
        condition: "DEFAULT"
    spec:
      ports:
      - name: default
        containerPort: 2567
        protocol: TCP
      health:
        disabled: false
        initialDelaySeconds: 30
        periodSeconds: 30
        failureThreshold: 3
      template:
        spec:
          containers:
          - image: gcr.io/forhumans-gameservices-dev/<NAME>:<BUILD_VERSION>
            imagePullPolicy: IfNotPresent
            livenessProbe:
              failureThreshold: 5
              httpGet:
                path: /liveness-check
                port: 2567
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
            name: <NAME>-<URL_VERSION>
            resources:
              requests:
                cpu: "0.2"
                memory: 1Gi
            volumeMounts:
            - mountPath: /var/secrets/google
              name: google-cloud-key
            - mountPath: /app/configuration
              name: config-files
          volumes:
          - name: google-cloud-key
            secret:
              defaultMode: 420
              secretName: gcp-api-key
          - configMap:
              defaultMode: 420
              name: config-<NAME>-<URL_VERSION>
            name: config-files
