'use strict';

module.exports = {
    ACCEPTED: 'ACCEPTED',
    REJECTED_ALREADY_OWNER: 'REJECTED_ALREADY_OWNER',
    REJECTED_INSUFFICIENT_MONEY: 'REJECTED_INSUFFICIENT_MONEY',
    REJECTED_STOP_POWER: 'REJECTED_STOP_POWER',
};